Repository GongAnts/GongAnts_Untact_Study_Room, pull requests merged in 2022-05, with the labels that each got.

#9 💎[!Breaking Change] 소셜 로그인 유저 회원가입 로직 구현 to develop
  .gitignore
  server/.env
  server/apidoc.json
  server/apidoc/auth.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/public/assets/android-chrome-192x192.png
  server/public/assets/android-chrome-512x512.png
  server/public/assets/apple-touch-icon.png
  server/public/assets/bootstrap.min.css
  server/public/assets/bootstrap.min.css.map
  server/public/assets/favicon-16x16.png
  server/public/assets/favicon-32x32.png
  server/public/assets/favicon.ico
  server/public/assets/glyphicons-halflings-regular.eot
  server/public/assets/glyphicons-halflings-regular.svg
  server/public/assets/glyphicons-halflings-regular.ttf
  server/public/assets/glyphicons-halflings-regular.woff
  server/public/assets/glyphicons-halflings-regular.woff2
  server/public/assets/main.bundle.js
  server/public/assets/main.css
  server/public/assets/prism.css
  server/public/index.html
  server/routes/memo.js
  server/routes/schedule.js
  server/routes/signup.js
  server/routes/studytime.js
  server/routes/todo.js
Labels: Done

#12 🚧[Refactor] 회원가입 아이디 중복 검사 로직 추가 및 메모 라우터 uri 변경 to develop
  server/apidoc/auth.js
  server/apidoc/memo.js
  server/public/assets/main.bundle.js
  server/routes/memo.js
  server/routes/signup.js
Labels: Done

#10 회원가입, 로그인 UI 구현 및 기능 구현
  .github/workflows/main.yml
  .gitignore
  README.md
  client/Documentation/.DS_Store
  client/Documentation/css/demo.css
  client/Documentation/css/documentation.css
  client/Documentation/css/light-bootstrap-dashboard.css
  client/Documentation/img/apple-icon.png
  client/Documentation/img/back.jpg
  client/Documentation/img/favicon.png
  client/Documentation/img/tim-logo.png
  client/Documentation/tutorial-components.html
  client/craco.config.js
  client/gulpfile.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/index.html
  client/src/App.js
  client/src/assets/img/photo-1431578500526-4d9613015464.jpeg
  client/src/components/.DS_Store
  client/src/index.js
  client/src/layouts/Admin.js
  client/src/layouts/signin/SignIn.js
  client/src/layouts/signup/SignUp.js
  client/src/layouts/styles.js
  client/src/redux/sagas/authsaga.js
  client/src/routes.js
  client/src/setupProxy.js
  client/src/styles/global.css
  client/src/views/UserProfile.js
  client/tailwind.config.js
Labels: In Progress

#16 🚧[Refactor] 일정 라우터 uri 변경 to develop
  server/apidoc.json
  server/apidoc/schedule.js
  server/routes/schedule.js
Labels: Back, Done

#17 🚧[Refactor] 할일 라우터 uri 변경
  server/apidoc.json
  server/public/assets/main.bundle.js
  server/routes/todo.js
Labels: In Progress
